Add RockPaperScissor() example
sharif-dev/android01 pull request #2
Opened 2019-02-07 13:00 UTC by ashmrz

یک مثال اضافه شد. البته من در پروژه‌ی اندروید نتوانستم آن را اجرا کنم. در یک پروژه‌ی جاوا آن را زدم و سپس به پروژه‌ی اصلی اضافه کردم و یکسری تغییرات دادم  و به جای پرینت‌ها، لاگ گذاشتم.

2019-02-08 10:02 UTC, Yumcoder-dev requested changes

2019-02-08 10:02 UTC, Yumcoder-dev commented on app/src/main/java/edu/sharif/prj01/rock_paper_scissor/Game.java
> +                while (p1 == null || p2 == null) {
can check p1 and p2 in out of the loop?

2019-02-08 10:02 UTC, Yumcoder-dev commented on app/src/main/java/edu/sharif/prj01/rock_paper_scissor/Game.java
> +                        wait();
never any thread send notify to it!

2019-02-08 10:02 UTC, Yumcoder-dev commented on app/src/main/java/edu/sharif/prj01/rock_paper_scissor/Game.java
> +                p1.eraseWeapon();
what is the application?

2019-02-08 10:02 UTC, Yumcoder-dev commented on app/src/main/java/edu/sharif/prj01/rock_paper_scissor/Game.java
> +                p2.eraseWeapon();
such as previous issue

2019-02-09 05:51 UTC, ashmrz commented on app/src/main/java/edu/sharif/prj01/rock_paper_scissor/Game.java
> +                while (p1 == null || p2 == null) {
fixed

2019-02-09 05:52 UTC, ashmrz commented on app/src/main/java/edu/sharif/prj01/rock_paper_scissor/Game.java
> +                        wait();
fixed

2019-02-09 06:05 UTC, closed without merging